export const GET_TODO_REQUEST = "GET_TOOD_REQUEST";
export const GET_TODO_SUCCESS = "GET_TOOD_SUCCESS";
export const GET_TODO_FAILURE = "GET_TOOD_FAILURE";

export const ADD_TODO_REQUEST = "ADD_TOOD_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TOOD_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TOOD_FAILURE";
export const UPDATE_ADD_TODO_REQUEST = "UPDATE_ADD_TOOD_REQUEST";

export const DELETE_TODO_REQUEST = "DELETE_TOOD_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TOOD_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TOOD_FAILURE";
export const UPDATE_DELETE_TODO_REQUEST = "UPDATE_DELETE_TOOD_REQUEST";

export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";
export const TOGGLE_TODO_REQUEST_CLEAR = "TOGGLE_TODO_REQUEST_CLEAR";
